import { Candidate, CVMode, ScoreTier, ApplicationStatus, LanguageLevel } from '@/types/candidate';
import { Job, ServiceType, JobStatus } from '@/types/job';
import { Commission, PayoutStatus, LedgerSummary, DuplicateSubmission } from '@/types/affiliate';

// ─── Mock Candidates ────────────────────────────────────────────────────────

export const MOCK_CANDIDATES: Candidate[] = [
  {
    id: 'cand-101',
    name: 'Nguyễn Văn A',
    email: 'nguyenvana.dev@gmail.com',
    phone: '+84901234567',
    linkedInUrl: 'https://linkedin.com/in/nguyenvana-dev',
    location: 'TP. Hồ Chí Minh, Việt Nam',
    currentTitle: 'Kỹ sư Backend Java cấp cao',
    currentCompany: 'Tập đoàn VNG',
    cvMode: CVMode.PLATFORM_BUILDER,
    skills: ['Java', 'Spring Boot', 'Kafka', 'PostgreSQL', 'Docker', 'Kubernetes', 'Redis', 'AWS'],
    industries: ['tech-software', 'tech-fintech'],
    highlightCard: {
      currentSalary: 35000000,
      expectedSalary: 55000000,
      currency: 'VND',
      yearsOfExperience: 7,
      primaryLanguage: 'Tiếng Anh',
      languageLevel: LanguageLevel.C1,
      availabilityDate: '2026-10-01',
      noticePeriod: 30,
      headline: '7 năm kinh nghiệm chuyên sâu Java/Spring, cựu kỹ sư VNG, thiết kế hệ thống thanh toán xử lý 2M TPS',
    },
    aiScore: 87,
    scoreTier: ScoreTier.TOP_FIT,
    applicationStatus: ApplicationStatus.SHORTLISTED,
    submittedBy: 'aff-001',
    firstSubmissionTimestamp: '2026-09-10T08:30:00Z',
    createdAt: '2026-09-10T08:30:00Z',
    updatedAt: '2026-09-15T10:00:00Z',
  },
  {
    id: 'cand-102',
    name: 'Trần Thị B',
    email: 'tranthib.fe@outlook.com',
    phone: '+84912345678',
    linkedInUrl: 'https://linkedin.com/in/tranthib-lead',
    location: 'Hà Nội, Việt Nam',
    currentTitle: 'Trưởng nhóm ReactJS / Kiến trúc sư Frontend',
    currentCompany: 'FPT Software',
    cvMode: CVMode.FILE_UPLOAD,
    cvUrl: '/mock-cvs/tranthib-cv.pdf',
    skills: ['React', 'TypeScript', 'Next.js', 'GraphQL', 'Storybook', 'Micro-frontends', 'Webpack', 'Jest'],
    industries: ['tech-software', 'tech-saas'],
    highlightCard: {
      currentSalary: 32000000,
      expectedSalary: 48000000,
      currency: 'VND',
      yearsOfExperience: 6,
      primaryLanguage: 'Tiếng Anh',
      languageLevel: LanguageLevel.B2,
      availabilityDate: '2026-10-15',
      noticePeriod: 45,
      headline: '6 năm kinh nghiệm ReactJS/TypeScript, kiến trúc sư Design System cho 12 nhóm dự án tại FPT Software',
    },
    aiScore: 74,
    scoreTier: ScoreTier.STRONG,
    applicationStatus: ApplicationStatus.SCREENING,
    submittedBy: 'aff-001',
    firstSubmissionTimestamp: '2026-09-12T09:15:00Z',
    createdAt: '2026-09-12T09:15:00Z',
    updatedAt: '2026-09-14T14:00:00Z',
  },
  {
    id: 'cand-103',
    name: 'Lê Minh Khoa',
    email: 'khoale.dev@gmail.com',
    phone: '+84923456789',
    location: 'Đà Nẵng, Việt Nam',
    currentTitle: 'Kỹ sư DevOps / Hạ tầng điện toán',
    currentCompany: 'MoMo',
    cvMode: CVMode.TEMPLATE_BASED,
    skills: ['Kubernetes', 'Terraform', 'AWS', 'GCP', 'Helm', 'ArgoCD', 'Prometheus', 'Grafana'],
    industries: ['tech-cloud', 'tech-saas'],
    highlightCard: {
      currentSalary: 28000000,
      expectedSalary: 42000000,
      currency: 'VND',
      yearsOfExperience: 5,
      primaryLanguage: 'Tiếng Anh',
      languageLevel: LanguageLevel.B1,
      availabilityDate: '2026-11-01',
      noticePeriod: 60,
      headline: '5 năm kinh nghiệm Cloud/DevOps, quản trị hạ tầng đa đám mây phục vụ 50 triệu người dùng tại MoMo',
    },
    aiScore: 65,
    scoreTier: ScoreTier.MODERATE,
    applicationStatus: ApplicationStatus.APPLIED,
    createdAt: '2026-09-14T11:00:00Z',
    updatedAt: '2026-09-14T11:00:00Z',
  },
  {
    id: 'cand-104',
    name: 'Phạm Quỳnh Như',
    email: 'nhu.pham@yahoo.com',
    phone: '+84934567890',
    location: 'TP. Hồ Chí Minh, Việt Nam',
    currentTitle: 'Kỹ sư Dữ liệu / Trưởng nhóm Phân tích',
    currentCompany: 'Shopee Việt Nam',
    cvMode: CVMode.PLATFORM_BUILDER,
    skills: ['Python', 'Spark', 'Airflow', 'dbt', 'Snowflake', 'BigQuery', 'Tableau', 'SQL'],
    industries: ['tech-data', 'tech-ecommerce'],
    highlightCard: {
      currentSalary: 30000000,
      expectedSalary: 45000000,
      currency: 'VND',
      yearsOfExperience: 5,
      primaryLanguage: 'Tiếng Anh',
      languageLevel: LanguageLevel.C1,
      availabilityDate: '2026-10-01',
      noticePeriod: 30,
      headline: '5 năm kinh nghiệm Data Engineering, xây dựng pipeline dữ liệu thời gian thực xử lý 500M sự kiện/ngày tại Shopee',
    },
    aiScore: 91,
    scoreTier: ScoreTier.TOP_FIT,
    applicationStatus: ApplicationStatus.INTERVIEW_SCHEDULED,
    submittedBy: 'aff-002',
    firstSubmissionTimestamp: '2026-09-08T07:00:00Z',
    createdAt: '2026-09-08T07:00:00Z',
    updatedAt: '2026-09-16T09:00:00Z',
  },
  {
    id: 'cand-105',
    name: 'Võ Tuấn Kiệt',
    email: 'kiet.vo@protonmail.com',
    phone: '+84945678901',
    location: 'TP. Hồ Chí Minh, Việt Nam',
    currentTitle: 'Giám đốc Sản phẩm Tăng trưởng (Product Manager)',
    currentCompany: 'Tiki',
    cvMode: CVMode.FILE_UPLOAD,
    skills: ['Product Strategy', 'OKR', 'SQL', 'A/B Testing', 'Figma', 'Jira', 'Analytics', 'Growth Hacking'],
    industries: ['tech-ecommerce', 'tech-saas'],
    highlightCard: {
      currentSalary: 35000000,
      expectedSalary: 55000000,
      currency: 'VND',
      yearsOfExperience: 6,
      primaryLanguage: 'Tiếng Anh',
      languageLevel: LanguageLevel.C1,
      availabilityDate: '2026-10-30',
      noticePeriod: 45,
      headline: '6 năm kinh nghiệm Quản trị Sản phẩm & Tăng trưởng, thúc đẩy tăng 40% GMV qua hệ thống cá nhân hóa tại Tiki',
    },
    aiScore: 55,
    scoreTier: ScoreTier.WEAK,
    applicationStatus: ApplicationStatus.APPLIED,
    createdAt: '2026-09-15T13:00:00Z',
    updatedAt: '2026-09-15T13:00:00Z',
  },
  {
    id: 'cand-106',
    name: 'Hoàng Bảo Long',
    email: 'baolong.hoang@gmail.com',
    phone: '+84956789012',
    location: 'Hà Nội, Việt Nam',
    currentTitle: 'Kỹ sư Lập trình Di động (iOS / React Native)',
    currentCompany: 'VinBrain',
    cvMode: CVMode.PLATFORM_BUILDER,
    skills: ['Swift', 'React Native', 'TypeScript', 'Firebase', 'CoreML', 'Fastlane', 'Xcode'],
    industries: ['tech-mobile', 'tech-healthtech'],
    highlightCard: {
      currentSalary: 26000000,
      expectedSalary: 38000000,
      currency: 'VND',
      yearsOfExperience: 4,
      primaryLanguage: 'Tiếng Anh',
      languageLevel: LanguageLevel.B2,
      availabilityDate: '2026-09-20',
      noticePeriod: 14,
      headline: '4 năm kinh nghiệm iOS/React Native, phát hành 3 ứng dụng y tế hàng đầu trên Vietnam App Store',
    },
    aiScore: 72,
    scoreTier: ScoreTier.STRONG,
    applicationStatus: ApplicationStatus.SCREENING,
    submittedBy: 'aff-001',
    firstSubmissionTimestamp: '2026-09-13T10:00:00Z',
    createdAt: '2026-09-13T10:00:00Z',
    updatedAt: '2026-09-13T10:00:00Z',
  },
  {
    id: 'cand-107',
    name: 'Dương Thị Mai',
    email: 'mai.duong@techsec.com',
    phone: '+84967890123',
    location: 'TP. Hồ Chí Minh, Việt Nam',
    currentTitle: 'Chuyên viên An toàn thông tin / Kiểm thử xâm nhập',
    currentCompany: 'Viettel Cyber Security',
    cvMode: CVMode.TEMPLATE_BASED,
    skills: ['Penetration Testing', 'SIEM', 'SOC', 'Python', 'Burp Suite', 'OSCP', 'AWS Security', 'ISO 27001'],
    industries: ['tech-cybersecurity', 'gov-federal'],
    highlightCard: {
      currentSalary: 32000000,
      expectedSalary: 50000000,
      currency: 'VND',
      yearsOfExperience: 6,
      primaryLanguage: 'Tiếng Anh',
      languageLevel: LanguageLevel.C1,
      availabilityDate: '2026-11-01',
      noticePeriod: 60,
      headline: '6 năm kinh nghiệm An toàn thông tin, chứng chỉ OSCP, chủ trì diễn tập Red Team cho 3 ngân hàng lớn',
    },
    aiScore: 83,
    scoreTier: ScoreTier.TOP_FIT,
    applicationStatus: ApplicationStatus.SHORTLISTED,
    submittedBy: 'aff-002',
    firstSubmissionTimestamp: '2026-09-09T14:00:00Z',
    createdAt: '2026-09-09T14:00:00Z',
    updatedAt: '2026-09-16T08:00:00Z',
  },
  // Duplicate pair for testing duplicate detection (same candidate, different affiliate)
  {
    id: 'cand-DUPE-A',
    name: 'Bùi Văn Hữu',
    email: 'huu.bui@candidate.com',
    phone: '+84978901234',
    location: 'TP. Hồ Chí Minh, Việt Nam',
    currentTitle: 'Kỹ sư Full Stack cấp cao',
    currentCompany: 'KMS Technology',
    cvMode: CVMode.FILE_UPLOAD,
    skills: ['Node.js', 'React', 'PostgreSQL', 'Docker', 'AWS', 'TypeScript'],
    industries: ['tech-software'],
    highlightCard: {
      currentSalary: 28000000,
      expectedSalary: 42000000,
      currency: 'VND',
      yearsOfExperience: 5,
      primaryLanguage: 'Tiếng Anh',
      languageLevel: LanguageLevel.B2,
      availabilityDate: '2026-10-01',
      noticePeriod: 30,
      headline: '5 năm kinh nghiệm Full Stack Node.js + ReactJS, cựu kỹ sư KMS, bàn giao 3 sản phẩm SaaS doanh nghiệp',
    },
    aiScore: 68,
    scoreTier: ScoreTier.MODERATE,
    applicationStatus: ApplicationStatus.APPLIED,
    submittedBy: 'aff-001',
    firstSubmissionTimestamp: '2026-09-05T09:00:00Z',
    createdAt: '2026-09-05T09:00:00Z',
    updatedAt: '2026-09-05T09:00:00Z',
  },
];

// Generate large candidate dataset for virtualization testing
export function generateLargeCandidateSet(count: number): Candidate[] {
  const titles = [
    'Kỹ sư Backend Java cấp cao', 'Trưởng nhóm ReactJS', 'Kỹ sư DevOps', 'Chuyên gia Khoa học Dữ liệu',
    'Giám đốc Sản phẩm (Product Manager)', 'Kỹ sư iOS', 'Kỹ sư Kiểm thử Tự động (QA Automation)', 'Scrum Master',
    'Kiến trúc sư Giải pháp (Solution Architect)', 'Kỹ sư Học máy (Machine Learning)', 'Kỹ sư Full Stack', 'Chuyên viên Thiết kế UX/UI',
    'Kỹ sư Node.js', 'Kỹ sư Python', 'Kiến trúc sư Đám mây', 'Chuyên viên Phân tích Nghiệp vụ (BA)',
  ];
  const companies = ['FPT Software', 'VNG', 'MoMo', 'Shopee', 'Tiki', 'VinBrain', 'KMS Tech', 'Base.vn', 'Grab', 'Lazada'];
  const locations = ['TP. Hồ Chí Minh', 'Hà Nội', 'Đà Nẵng', 'Cần Thơ', 'Bình Dương'];
  const statuses = Object.values(ApplicationStatus);
  const tiers = Object.values(ScoreTier);

  return Array.from({ length: count }, (_, i) => ({
    id: `cand-gen-${i + 1}`,
    name: `Ứng viên ${i + 1}`,
    email: `ungvien${i + 1}@example.com`,
    phone: `+8490${String(i).padStart(7, '0')}`,
    location: `${locations[i % locations.length]}, Việt Nam`,
    currentTitle: titles[i % titles.length],
    currentCompany: companies[i % companies.length],
    cvMode: CVMode.PLATFORM_BUILDER,
    skills: ['JavaScript', 'TypeScript', 'React'],
    industries: ['tech-software'],
    highlightCard: {
      currentSalary: 20000000 + (i % 30) * 1500000,
      expectedSalary: 28000000 + (i % 30) * 2000000,
      currency: 'VND' as const,
      yearsOfExperience: 1 + (i % 15),
      primaryLanguage: 'Tiếng Anh',
      languageLevel: LanguageLevel.B2,
      availabilityDate: '2026-10-01',
      noticePeriod: 30,
      headline: `${1 + (i % 15)} năm kinh nghiệm ${titles[i % titles.length]}`,
    },
    aiScore: Math.floor(40 + (i % 60)),
    scoreTier: tiers[i % tiers.length],
    applicationStatus: statuses[i % statuses.length],
    createdAt: new Date(Date.now() - i * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - i * 43200000).toISOString(),
  }));
}

// ─── Mock Jobs ───────────────────────────────────────────────────────────────

export const MOCK_JOBS: Job[] = [
  {
    id: 'job-001',
    title: 'Kỹ sư Backend Java cấp cao (Senior Java Backend)',
    company: 'TechCorp Việt Nam',
    companyId: 'client-001',
    industryCode: 'tech-software',
    industryLabel: 'Phát triển Phần mềm',
    serviceType: ServiceType.HEADHUNT_COD,
    status: JobStatus.ACTIVE,
    location: 'TP. Hồ Chí Minh, Việt Nam',
    remote: false,
    salaryRange: { min: 45000000, max: 70000000, currency: 'VND', negotiable: true },
    mustHaveTags: ['Java', 'Spring Boot', 'PostgreSQL', '5+ năm kinh nghiệm'],
    shouldHaveTags: ['Kafka', 'Kubernetes', 'AWS', 'Microservices'],
    objectives: 'Xây dựng và mở rộng hệ thống backend cho cổng thanh toán B2B xử lý trên 5 triệu giao dịch mỗi ngày',
    engagementTerms: { timeline: 30, commissionRate: 18, retainerFee: 0, budget: 0 },
    headcount: 2,
    experienceYears: { min: 5, max: 10 },
    description: 'Chúng tôi đang tìm kiếm Kỹ sư Backend Java cấp cao gia nhập đội ngũ nòng cốt phát triển giải pháp thanh toán điện tử...',
    requirements: ['5+ năm kinh nghiệm Java', 'Kiến trúc microservices với Spring Boot', 'Thiết kế hệ thống chịu tải cao'],
    createdAt: '2026-09-01T08:00:00Z',
    updatedAt: '2026-09-15T10:00:00Z',
    deadline: '2026-10-15T00:00:00Z',
    clientContactId: 'client-001',
    internalHRId: 'hr-001',
    applicationCount: 24,
    shortlistedCount: 5,
  },
  {
    id: 'job-002',
    title: 'Trưởng nhóm ReactJS / Kiến trúc sư Frontend',
    company: 'DigitalWave Agency',
    companyId: 'client-002',
    industryCode: 'tech-saas',
    industryLabel: 'Phần mềm dịch vụ (SaaS)',
    serviceType: ServiceType.HEADHUNT_COD,
    status: JobStatus.ACTIVE,
    location: 'Hà Nội, Việt Nam (Hybrid)',
    remote: true,
    salaryRange: { min: 40000000, max: 65000000, currency: 'VND', negotiable: true },
    mustHaveTags: ['React', 'TypeScript', 'Kinh nghiệm thiết kế kiến trúc', '5+ năm kinh nghiệm'],
    shouldHaveTags: ['Next.js', 'Micro-frontends', 'Storybook', 'GraphQL'],
    objectives: 'Chủ trì kiến trúc frontend cho sản phẩm SaaS thế hệ mới phục vụ hơn 100.000 người dùng doanh nghiệp',
    engagementTerms: { timeline: 45, commissionRate: 15, retainerFee: 12000000, budget: 0 },
    headcount: 1,
    experienceYears: { min: 5, max: 8 },
    description: 'Tìm kiếm Trưởng nhóm ReactJS kiến trúc toàn bộ giao diện và dẫn dắt đội ngũ kỹ sư frontend...',
    requirements: ['5+ năm kinh nghiệm React/TypeScript', 'Thiết kế kiến trúc hệ thống', 'Kỹ năng lãnh đạo đội nhóm'],
    createdAt: '2026-09-05T09:00:00Z',
    updatedAt: '2026-09-14T11:00:00Z',
    deadline: '2026-10-20T00:00:00Z',
    clientContactId: 'client-002',
    internalHRId: 'hr-001',
    applicationCount: 18,
    shortlistedCount: 3,
  },
  {
    id: 'job-003',
    title: 'Kỹ sư Dữ liệu — Nền tảng Phân tích (Data Engineer)',
    company: 'Tập đoàn Bán lẻ RetailGiant',
    companyId: 'client-003',
    industryCode: 'tech-data',
    industryLabel: 'Hạ tầng Dữ liệu & Phân tích',
    serviceType: ServiceType.CV_SOURCING,
    status: JobStatus.ACTIVE,
    location: 'TP. Hồ Chí Minh, Việt Nam',
    remote: false,
    salaryRange: { min: 35000000, max: 50000000, currency: 'VND', negotiable: false },
    mustHaveTags: ['Python', 'Spark', 'SQL', '4+ năm kinh nghiệm'],
    shouldHaveTags: ['Airflow', 'dbt', 'Snowflake', 'BigQuery'],
    objectives: 'Xây dựng đường ống dữ liệu phân tích thời gian thực cho chuỗi bán lẻ toàn quốc',
    engagementTerms: { timeline: 20, commissionRate: 12, retainerFee: 0, budget: 120000000 },
    headcount: 3,
    experienceYears: { min: 4, max: 8 },
    description: 'Vị trí Kỹ sư Dữ liệu phụ trách xây dựng và vận hành các pipeline dữ liệu quy mô lớn...',
    requirements: ['4+ năm kinh nghiệm kỹ thuật dữ liệu', 'Chuyên sâu Python/Spark', 'Thành thạo tối ưu SQL'],
    createdAt: '2026-09-08T10:00:00Z',
    updatedAt: '2026-09-13T09:00:00Z',
    deadline: '2026-10-01T00:00:00Z',
    clientContactId: 'client-003',
    applicationCount: 32,
    shortlistedCount: 8,
  },
  {
    id: 'job-004',
    title: 'Chuyên viên An toàn thông tin (Cybersecurity Engineer)',
    company: 'Ngân hàng FinSecure',
    companyId: 'client-004',
    industryCode: 'fin-banking',
    industryLabel: 'Tài chính Ngân hàng',
    serviceType: ServiceType.HEADHUNT_COD,
    status: JobStatus.ACTIVE,
    location: 'TP. Hồ Chí Minh, Việt Nam',
    remote: false,
    salaryRange: { min: 50000000, max: 80000000, currency: 'VND', negotiable: true },
    mustHaveTags: ['Chứng chỉ OSCP/CISSP', 'Kiểm thử xâm nhập', 'Kinh nghiệm SOC', '6+ năm kinh nghiệm'],
    shouldHaveTags: ['ISO 27001', 'SIEM', 'Bảo mật Đám mây', 'Nghiệp vụ Ngân hàng'],
    objectives: 'Tăng cường thế trận an ninh mạng và chủ trì các chiến dịch Red Team định kỳ',
    engagementTerms: { timeline: 30, commissionRate: 20, retainerFee: 25000000, budget: 0 },
    headcount: 1,
    experienceYears: { min: 6, max: 12 },
    description: 'Chuyên viên An toàn thông tin cấp cao phụ trách hệ thống hạ tầng ngân hàng bảo mật...',
    requirements: ['Chứng chỉ OSCP hoặc CISSP', '6+ năm kinh nghiệm an toàn thông tin', 'Am hiểu quy chuẩn bảo mật tài chính ngân hàng'],
    createdAt: '2026-09-10T11:00:00Z',
    updatedAt: '2026-09-15T08:00:00Z',
    deadline: '2026-11-01T00:00:00Z',
    clientContactId: 'client-004',
    internalHRId: 'hr-001',
    applicationCount: 11,
    shortlistedCount: 2,
  },
  {
    id: 'job-005',
    title: 'Kỹ sư DevOps / Hạ tầng nền tảng (Platform Engineer)',
    company: 'CloudNative Labs',
    companyId: 'client-005',
    industryCode: 'tech-cloud',
    industryLabel: 'Điện toán Đám mây',
    serviceType: ServiceType.CV_APPLICATION,
    status: JobStatus.ACTIVE,
    location: 'Làm việc từ xa — Toàn quốc',
    remote: true,
    salaryRange: { min: 30000000, max: 48000000, currency: 'VND', negotiable: true },
    mustHaveTags: ['Kubernetes', 'Terraform', 'CI/CD', '3+ năm kinh nghiệm'],
    shouldHaveTags: ['ArgoCD', 'Helm', 'AWS/GCP', 'Prometheus'],
    objectives: 'Xây dựng và vận hành nền tảng Kubernetes đa đám mây phục vụ hàng trăm dịch vụ',
    engagementTerms: { timeline: 15, commissionRate: 0, retainerFee: 0, budget: 0 },
    headcount: 2,
    experienceYears: { min: 3, max: 7 },
    description: 'Tìm kiếm Kỹ sư DevOps gia nhập startup công nghệ điện toán đám mây tiên phong...',
    requirements: ['3+ năm kinh nghiệm DevOps', 'Vận hành Kubernetes cấp độ chuyên sâu', 'Tự động hóa với Terraform IaC'],
    createdAt: '2026-09-12T07:00:00Z',
    updatedAt: '2026-09-12T07:00:00Z',
    deadline: '2026-09-30T00:00:00Z',
    clientContactId: 'client-005',
    applicationCount: 45,
    shortlistedCount: 10,
  },
];

// ─── Mock Financial Ledger ────────────────────────────────────────────────────

export const MOCK_COMMISSIONS: Commission[] = [
  {
    id: 'com-001',
    affiliateId: 'aff-001',
    affiliateName: 'David Tran',
    candidateId: 'cand-101',
    candidateName: 'Nguyễn Văn A',
    jobId: 'job-001',
    jobTitle: 'Kỹ sư Backend Java cấp cao',
    companyName: 'TechCorp Việt Nam',
    commissionRate: 18,
    baseSalary: 55000000,
    commissionAmount: 59400000, // 55,000,000 * 0.18 * 6
    currency: 'VND',
    status: PayoutStatus.ON_HOLD,
    hiredAt: '2026-08-15T00:00:00Z',
    probationStartDate: '2026-08-15T00:00:00Z',
    probationEndDate: '2026-10-14T00:00:00Z',
    probationDaysRemaining: 27,
    probationProgress: 55,
    warrantyExpired: false,
  },
  {
    id: 'com-002',
    affiliateId: 'aff-001',
    affiliateName: 'David Tran',
    candidateId: 'cand-107',
    candidateName: 'Dương Thị Mai',
    jobId: 'job-004',
    jobTitle: 'Chuyên viên An toàn thông tin',
    companyName: 'Ngân hàng FinSecure',
    commissionRate: 20,
    baseSalary: 65000000,
    commissionAmount: 78000000,
    currency: 'VND',
    status: PayoutStatus.PAYABLE,
    hiredAt: '2026-06-01T00:00:00Z',
    probationStartDate: '2026-06-01T00:00:00Z',
    probationEndDate: '2026-07-31T00:00:00Z',
    probationDaysRemaining: 0,
    probationProgress: 100,
    warrantyExpired: true,
    payoutRequestedAt: undefined,
  },
  {
    id: 'com-003',
    affiliateId: 'aff-001',
    affiliateName: 'David Tran',
    candidateId: 'cand-104',
    candidateName: 'Phạm Quỳnh Như',
    jobId: 'job-003',
    jobTitle: 'Kỹ sư Dữ liệu',
    companyName: 'Tập đoàn Bán lẻ RetailGiant',
    commissionRate: 12,
    baseSalary: 45000000,
    commissionAmount: 32400000,
    currency: 'VND',
    status: PayoutStatus.PAID,
    hiredAt: '2026-04-01T00:00:00Z',
    probationStartDate: '2026-04-01T00:00:00Z',
    probationEndDate: '2026-05-31T00:00:00Z',
    probationDaysRemaining: 0,
    probationProgress: 100,
    warrantyExpired: true,
    paidAt: '2026-06-05T10:00:00Z',
    bankDetails: {
      bankName: 'Vietcombank',
      accountNumber: '0071001234567',
      accountHolder: 'DAVID TRAN',
      swiftCode: 'BFTVVNVX',
    },
    payoutEvidence: {
      bankReferenceCode: 'VCB-FT26156983021',
      paidAmount: 32400000,
      transferDate: '2026-06-05',
      receiptImageUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=1000&q=80',
      receiptFileName: 'UNC_VCB_32400000VND_DavidTran.pdf',
      receiptFileSize: '428 KB',
      bankName: 'Vietcombank (VCB)',
      accountNumber: '0071001234567',
      accountHolder: 'DAVID TRAN',
      recordedBy: 'Alex Nguyen (Platform Admin)',
      recordedAt: '2026-06-05T10:15:00Z',
      adminNotes: 'Đã hoàn tất lệnh chuyển khoản qua VCB Chi nhánh TP.HCM. Ủy nhiệm chi số UNC-06/2026-88.',
    },
    auditTrail: [
      {
        id: 'aud-001',
        action: 'CREATED_LEDGER_ITEM',
        actorName: 'System Engine',
        actorRole: 'SYSTEM',
        timestamp: '2026-04-01T00:00:00Z',
        details: 'Khởi tạo khoản hoa hồng tự động khi ứng viên Phạm Quỳnh Như nhận việc tại Tập đoàn Bán lẻ RetailGiant.',
      },
      {
        id: 'aud-002',
        action: 'WARRANTY_COMPLETED',
        actorName: 'Warranty Automation Job',
        actorRole: 'SYSTEM',
        timestamp: '2026-05-31T23:59:59Z',
        details: 'Hoàn thành 60/60 ngày thử việc không phát sinh tranh chấp. Chuyển trạng thái từ Chờ duyệt sang Đủ điều kiện nhận.',
        previousStatus: PayoutStatus.ON_HOLD,
        newStatus: PayoutStatus.PAYABLE,
      },
      {
        id: 'aud-003',
        action: 'OFFLINE_PAYOUT_RECORDED',
        actorName: 'Alex Nguyen (Platform Admin)',
        actorRole: 'ADMIN',
        timestamp: '2026-06-05T10:15:00Z',
        details: 'Ghi nhận chuyển khoản ngoài ngân hàng Vietcombank. Mã GD: VCB-FT26156983021. Đính kèm ủy nhiệm chi UNC_VCB_32400000VND_DavidTran.pdf.',
        previousStatus: PayoutStatus.PAYABLE,
        newStatus: PayoutStatus.PAID,
      },
    ],
  },
  {
    id: 'com-004',
    affiliateId: 'aff-001',
    affiliateName: 'David Tran',
    candidateId: 'cand-102',
    candidateName: 'Trần Thị B',
    jobId: 'job-002',
    jobTitle: 'Trưởng nhóm ReactJS / Kiến trúc sư Frontend',
    companyName: 'DigitalWave Agency',
    commissionRate: 15,
    baseSalary: 48000000,
    commissionAmount: 43200000,
    currency: 'VND',
    status: PayoutStatus.ON_HOLD,
    hiredAt: '2026-09-01T00:00:00Z',
    probationStartDate: '2026-09-01T00:00:00Z',
    probationEndDate: '2026-10-31T00:00:00Z',
    probationDaysRemaining: 44,
    probationProgress: 26,
    warrantyExpired: false,
  },
];

export const MOCK_LEDGER_SUMMARY: LedgerSummary = {
  pendingAmount: 102600000,
  payableAmount: 78000000,
  paidAmount: 32400000,
  totalEarned: 213000000,
  currency: 'VND',
  totalPlacements: 4,
  activeProbations: 2,
};

// ─── Duplicate Submission Mock ─────────────────────────────────────────────

export const KNOWN_DUPLICATES: DuplicateSubmission[] = [
  {
    originalSubmissionId: 'sub-001',
    originalAffiliateId: 'aff-001',
    originalAffiliateName: 'David Tran',
    originalTimestamp: '2026-09-05T09:00:00Z',
    duplicateAffiliateId: 'aff-current',
    duplicateAffiliateName: 'Bạn',
    duplicateTimestamp: '',
    candidateEmail: 'huu.bui@candidate.com',
    candidatePhone: '+84978901234',
    jobId: 'job-001',
    status: 'BLOCKED',
  },
];

// Check if a candidate submission is a duplicate
export function checkDuplicate(
  email: string,
  phone: string,
  jobId: string
): DuplicateSubmission | null {
  const normalizedEmail = email.toLowerCase().trim();
  const normalizedPhone = phone.replace(/\s+/g, '');

  return (
    KNOWN_DUPLICATES.find(
      (d) =>
        (d.candidateEmail === normalizedEmail || d.candidatePhone === normalizedPhone) &&
        d.jobId === jobId
    ) ?? null
  );
}

// ─── Screening Results ─────────────────────────────────────────────────────

export const MOCK_SCREENING_RESULTS = [
  {
    candidateId: 'cand-101',
    jobId: 'job-001',
    semanticScore: 87,
    scoreTier: ScoreTier.TOP_FIT,
    matchedSkills: ['Java', 'Spring Boot', 'PostgreSQL', 'Kafka', 'Docker'],
    missingSkills: ['Kubernetes (mới ở mức làm quen cơ bản)'],
    aiSummary:
      'Nguyễn Văn A là ứng viên có độ phù hợp xuất sắc cho vị trí Kỹ sư Backend Java cấp cao. Với 7 năm kinh nghiệm tại VNG trong môi trường kỹ thuật đòi hỏi cao, ứng viên hoàn toàn đáp ứng yêu cầu phát triển nền tảng thanh toán. Kinh nghiệm dẫn dắt hệ thống xử lý 2 triệu giao dịch/giây (2M TPS) chứng minh năng lực chuyên sâu về kiến trúc phân tán quy mô lớn.',
    strengths: [
      'Chuyên môn sâu về hệ sinh thái Java / Spring Boot khớp hoàn toàn tiêu chí bắt buộc có',
      'Kinh nghiệm thực chiến thiết kế hệ thống thanh toán thông lượng cao (2M TPS)',
      'Thành thạo Kafka, cơ sở dữ liệu phân tán và kiến trúc microservices',
      'Sẵn sàng nhận việc sớm (01/10/2026)',
    ],
    concerns: ['Kinh nghiệm Kubernetes ở mức cơ bản — có thể cần đào tạo bổ sung ngắn hạn'],
    recommendation: 'KHUYẾN NGHỊ CAO duyệt hồ sơ phỏng vấn. Cần sắp xếp phỏng vấn kỹ thuật trong vòng 5 ngày làm việc để tránh rủi ro ứng viên nhận đề nghị từ đơn vị khác.',
    screenedAt: '2026-09-15T14:00:00Z',
    screenedBy: 'AI' as const,
  },
];
