export { JobCard, type JobCardData, formatSalaryVND, deduplicateTags } from './common/JobCard';
export { JobCardHorizontal } from './common/JobCardHorizontal';
export { JobDetailModal } from './common/JobDetailModal';
export { CompanyLogo, getCompanyLogoUrl } from './common/CompanyLogo';
export { AppStatusBadge, PayoutStatusBadge } from './common/StatusBadge';
export { RoleBadge } from './common/RoleBadge';
export { ScoreTierTag } from './common/ScoreTierTag';
export { AntiDuplicationBadge } from './common/AntiDuplicationBadge';
export { FintechMetricCard } from './common/FintechMetricCard';
export { LanguageSwitcher } from './common/LanguageSwitcher';
